[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200

; Necessary for the Super Mini to show Serial output over USB
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Add these dependencies so PlatformIO downloads the gyro drivers automatically
lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    Wire
